<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \CND\Baker\Block\BakerData $block */
?>
<script type="text/x-magento-init">
<?= /* @noEscape */ $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonEncode([
        '*' => ['CND_Baker/js/baker-data' => [
            'sectionLoadUrl' => $block->getBakerDataUrl('baker/section/load'),
            'expirableSectionLifetime' => $block->getExpirableSectionLifetime(),
            'expirableSectionNames' => $block->getExpirableSectionNames(),
            'cookieLifeTime' => $block->getCookieLifeTime(),
            'updateSessionUrl' => $block->getBakerDataUrl('baker/account/updateSession'),
        ]],
    ]);
?>
</script>
