<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \CND\Baker\Block\SectionConfig $block */
?>
<script type="text/x-magento-init">
<?= /* @noEscape */ $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonEncode([
        '*' => ['CND_Baker/js/section-config' => [
            'sections' => $block->getSections(),
            'clientSideSections' => $block->getClientSideSections(),
            'baseUrls' => array_unique([
                $block->getUrl(null, ['_secure' => true]),
                $block->getUrl(null, ['_secure' => false]),
            ]),
        ]],
    ]);
?>
</script>
