<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var CND\Baker\Block\Account\Baker $block */
?>
<?php if($block->bakerLoggedIn()): ?>
    <li class="baker-welcome">
        <span class="baker-name"
              role="link"
              tabindex="0"
              data-mage-init='{"dropdown":{}}'
              data-toggle="dropdown"
              data-trigger-keypress-button="true"
              data-bind="scope: 'baker'">
            <span data-bind="text: baker().fullname"></span>
            <button type="button"
                    class="action switch"
                    tabindex="-1"
                    data-action="baker-menu-toggle">
                <span><?= $block->escapeHtml(__('Change')) ?></span>
            </button>
        </span>
        <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "baker": {
                            "component": "CND_Baker/js/view/baker"
                        }
                    }
                }
            }
        }
        </script>
        <?php if($block->getChildHtml()):?>
        <div class="baker-menu" data-target="dropdown">
            <?= $block->getChildHtml() ?>
        </div>
        <?php endif; ?>
    </li>
<?php endif; ?>
