<?php
/**
 * Created by PhpStorm.
 * User: Vivek Ramasha
 * Date: 15-06-2018
 * Time: 02:03 PM
 */
?>
<div class="container">
    <!-- /.row -->
    <div class="well divpadding">
        <h4><b>Welcome Stephen Lee</b></h4>
        <p class="form-control-static">
You are just few steps away from setting up your business with us. Listed below are the steps to complete your sign up process.
        </p>
    </div>
    <div class="well">
        <div class="checkbox w3-xxlarge"><i class="fa fa-check-square  text-red" ></i></div>
        <h4><b>1. Tell us more</b></h4>
        <p class="form-control-static">
Tell us more about your business, how long you been doing it, your specialities to understand and help you get the customers you will love to serve.
        </p><hr class="hr1">
        <div  class=" btn btn-link pull-right " ><a class="link " href="profile">Get Started</a></div>
        <div></div></div>
        <div class="well">
            <div class="checkbox w3-xxlarge"><i class="fa fa-check-square" ></i></div>

            <h4><b>2. Submit for Verification</b></h4>
            <p class="form-control-static">
We will get in touch with you to understand your business and services. Once we are aligned, you will be able to start serving our customers you will love to serve.</p>
        </div>
        <div class="well">
            <div class="checkbox w3-xxlarge"><i class="fa fa-check-square" ></i></div>
            <h4><b>4. Backgroud check</b></h4>
            <p class="form-control-static">
We will get in touch with you to understand pur business and services. Once we are aligned, pu will be able start serving our customers.</p>
        </div>
        <div class="well">
            <div class="checkbox w3-xxlarge"><i class="fa fa-check-square" ></i></div>
            <h4><b>5. Build your Business Profile</b></h4>

            <p class="form-control-static">
Once your account is approved. You can start building your business profile on our plarform. You can showcase all your best works, display your services and what not - all you can do to get more customers !!</p>
        </div>
        <div class="well">
            <div class="checkbox w3-xxlarge"><i class="fa fa-check-square" "></i></div>
            <h4><b>6. Your first Order !</b></h4>
            <p class="form-control-static">Once your account is approved, you will be able to browse through the customer requests and bid for them.</p></div>
            <div class="col-md-12">
                <h4 class="text-center">Got any Questions?</h4>
                <p class="form-control-static text-justify">Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Integer posuere erata ante venenatis dapibus posuere velit aliquet. Maecenas faucibus modis interdum. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
            </div>
        </div>