<?php
/** @var \CND\HomeModule\Block\Baker $block */

$block->getConfig("")
?>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<div class="container" >

    <div class="row">
        <div class="col-md-6 divpadding text-center">
            <h3><b>Looking for a custom cake for your party?</b></h3>
            <p class="form-control-static" >You have reached the right place.</p>
            <div class="col-md-10 ">
                <button type="button" class="button btn-block">Create an Order</button>
            </div>

            <div class="col-md-12">
                <a href="#" class="alink btn btn-link" >Sign In</a>
                <a href="#" class='alink btn btn-link'>Register as a Customer</a>
            </div>

        </div>

    </div>




    <!-- /.row -->

</div>

</body>

</html>