<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \CND\Baker\Block\Widget\Dob $block */

/*
<?= $block->getLayout()->createBlock('CND\Baker\Block\Widget\Dob')
   ->setDate($block->getBaker()->getDob())
   ->toHtml() ?>

For checkout/onepage/billing.phtml:

<?= $block->getLayout()->createBlock('CND\Baker\Block\Widget\Dob')
   ->setDate($block->getBaker()->getDob())
   ->setFieldIdFormat('billing:%s')
   ->setFieldNameFormat('billing[%s]')
   ->toHtml() ?>

NOTE: Regarding styles - if we leave it this way, we'll move it to boxes.css. Alternatively we could calculate widths
automatically using block input parameters.
*/

$fieldCssClass = 'field date field-' . $block->getHtmlId();
$fieldCssClass .= $block->isRequired() ? ' required' : '';
?>
<div class="<?= $block->escapeHtmlAttr($fieldCssClass) ?>">
    <label class="label" for="<?= $block->escapeHtmlAttr($block->getHtmlId()) ?>"><span><?= $block->escapeHtml($block->getLabel()) ?></span></label>
    <div class="control baker-dob">
        <?= $block->getFieldHtml() ?>
        <?php if ($_message = $block->getAdditionalDescription()) : ?>
            <div class="note"><?= $block->escapeHtml($_message) ?></div>
        <?php endif; ?>
    </div>
</div>
