<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/* @var $block \CND\Baker\Block\BakerScopeData */
?>
<script type="text/x-magento-init">
<?php
    /* @noEscape */
    echo \Magento\Framework\Serialize\JsonConverter::convert([
        '*' => ['CND_Baker/js/invalidation-processor' => [
            'invalidationRules' => [
                'website-rule' => [
                    'CND_Baker/js/invalidation-rules/website-rule' => [
                        'scopeConfig' => [
                            'websiteId' => $block->getWebsiteId(),
                        ]
                    ]
                ]
            ]
        ]],
    ]);
    ?>
</script>
